### ISSUE TITLE
ExternalImage breaks Code fields on Safari

### ISSUE THREAD

**Issue by ralphschindler** [chaseconey/nova-external-image#3]
I hate to drive by and file an issue, but I've noticed this is an issue purely with safari (works in Chrome).

When adding `ExternalImage` into a Nova Resource that is also using `Code`, all of the `Code` fields (on a Detail page) fail to render.  There are no console errors.. I've not been able to figure out what is blocking what.  Attached is a screenshot.

I can do my best to drill down to the issue if you want me to try something.

![nova site without externalimage](https://user-images.githubusercontent.com/76674/50705493-9ec1a700-1020-11e9-831b-64c310d7361a.png)

![nova site with externalimage](https://user-images.githubusercontent.com/76674/50705499-a3865b00-1020-11e9-93f1-28b714519a05.png)

**Comment by joeelia** [comment]
This doesn't happen to me, but I don't have that field you're using above the External Image package. Have you tied it without your custom 'Syndicate Title' field?

Edit: Tested on Safari 12.0.2

**Comment by ralphschindler** [comment]
It was a problem with the Code field, that was fixed and this problem went away. Closing.
