### ISSUE TITLE
size directives doesn't work in detail view

### ISSUE THREAD

**Issue by chilio** [chaseconey/nova-external-image#6]
Really nice addon to Nova, thank you for that @chaseconey .
I believe the title is enough explanatory itself, therefore I'm not bloating the description.
My versions:
PHP: 7.3.4
Laravel: 7.1
Nova: 3.0.1

**Comment by man-dwarf** [comment]
Same issue

**Comment by chaseconey** [comment]
This should be fixed in version `0.3.0`. Thanks for reporting!

**Comment by chilio** [comment]
@chaseconey thanks. I can confirm that it works as expected in `0.3.0`.
